### ISSUE TITLE
Usage of ulong32

### ISSUE THREAD

**Issue by seppeon** [iboB/mscharconv#1]
Hello!

Recommend changing ulong32 to use cstdint's uint32_t. uint32_t is needed be some of the builtin's used and gets flagged as a conversion error on latest clang.
I've also added some static_casts in order to allow compilation under werror.

[msstl.zip](https://github.com/iboB/mscharconv/files/7566917/msstl.zip)

**Comment by iboB** [comment]
Hi and thanks for the patch.

This is GitHub so it makes life much easier if instead of a patch, one submits a pull request (PR). Basically you need to fork the repo, make the changes in your fork, and submit a PR to the source repo. Had this been a PR, a whole code-review workflow would have been enabled and also GitHub actions would have been run to build the PR in question. More on this here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

As for the proposed changes:

* Replacing `ulong32` with `uint32_t` - I really don't get. It should be a noop change. Instead of defining `msstl::impl::ulong32` it defines `msstl::impl::uint32_t` to the exact same thing. I use `ulong32` to explicitly mark places where Microsoft used `unsigned long` relying that it's 32-bit (which is the case in MSVC)
* Replacing `__builtin_c?zl` with `__builtin_c?zll`: this is perhaps because you're dealing with a standard library which defines `uint64_t` to `unsigned long long`. Libstdc++ defines it to simply `unsigned long`. If this is the case, the correct approach would be to use `if (constexpr std::is_same_v<uint64_t, unsigned long>)` to select the correct builtin
* As for the static casts added in the code, this is a bigger problem. I would very much like to keep the conversion of the files from ms/STL automated so this library can be updated as the source one is. Manually making changes to the generated files is not the way to go. If these are real problems, perhaps instead of requesting changes here, you should make a PR to https://github.com/microsoft/STL

Actually it just dawned on me! Are you building a 32 bit executable? This might actually be it. I'll make an experiment to check.

**Comment by iboB** [comment]
OK. So I made some commits addressing the issues you describe. 

Let me know if the latest master works for you

**Comment by iboB** [comment]
No response from OP here, but I think the issues were resolved. Closing

**Comment by iboB** [comment]
@seppeon feel free to reopen or post another issue if you think I've missed something

**Comment by seppeon** [comment]
Thanks! I'll check on the weekend! (friday for me)
Thankyou! Hope my patch was useful!
